---
# tasks file for jenkins
- name: Update the software package repository
  yum:
    name: "*"
    update_cache: yes

- name: Removing old version of JAVA from Amazon Linux
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: Install specific supported version of JAVA
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Add Jenkins repository
  command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present

- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started

- wait_for:
    port: 8080
    command: cat /var/lib/jenkins/secrets/initialAdminPassword

- name: Get Admin Password
  become: yes
  become_method: sudo
  command: cat /var/lib/jenkins/secrets/initialAdminPassword



